services:

  db:
    image: postgres:15
    container_name: nytimes-db
    restart: always
    environment:
      POSTGRES_DB: nytimes
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password

    secrets:
      - db_user
      - db_password

    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: ../prj_python-api-nytimes/api
    container_name: nytimes-api
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://nytimes:nytimes@db:5432/nytimes
    ports:
      - "8000:8000"


  scraper:
    build: ../prj_python-rpa-nytimes-scraper
    container_name: nytimes-scraper 
    depends_on:
      - api
    environment:
      API_BASE_URL: http://api:8000

secrets:
  db_user:
    file: ./secrets/db_user.txt
  db_password:
    file: ./secrets/db_password.txt

volumes:
  pgdata:






